:open: &#91;
:close: &#93;
:otap: {open}|-acc|-test{close}
= The POMS ecosystem
:toc:

image:https://github.com/npo-poms/poms-parent/workflows/build/badge.svg?[Build Status,link=https://github.com/npo-poms/poms-parent/actions?query=workflow%3Abuild]
image:https://img.shields.io/maven-central/v/nl.vpro.poms/poms-parent.svg?label=Maven%20Central[Maven Central,link=https://search.maven.org/search?q=g:%22nl.vpro.poms%22%20AND%20a:%22poms-parent%22]
image:https://img.shields.io/nexus/s/https/oss.sonatype.org/nl.vpro.poms/poms-parent.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/nl/vpro/poms/poms-parent/]

This is the poms parent. This is the parent pom of the several projects in the poms ('Publieke Omroep Media Services') ecosystem, which are used by dutch public broadcasters.

We use the `pom.xml` of this project to synchronize versions of dependencies.

This README serves as a general description of the different systems that this envolves

We're available at link:https://vpro-poms.slack.com/[slack].

Documentation is maintained at https://wiki.vpro.nl/display/poms/[wiki of NPO] (needs password, and your ip in proper range)

== Deployments

This describes schematicly the connections between actual systems relevant to poms.

This does not intend to be exhaustive, but merely tries to sketch the big picture. Especially the part 'World' contains mainly examples.
image:https://rawgit.com/npo-poms/poms-parent/master/poms-deployment.svg[title=deployment, link=https://rawgit.com/npo-poms/poms-parent/master/poms-deployment.svg, window="_blank"]


== Dependencies

This describes schematicly the dependencies between the several modules relevant to poms.

This does not intend to be exhaustive, but merely tries to sketch the big picture.

An important aspect is that dependencies may only be one way and non circular. Often dependencies are both transitive and direct, of which only examples are indicated.


image:https://rawgit.com/npo-poms/poms-parent/master/poms-dependencies.svg[title=dependencies, link=https://rawgit.com/npo-poms/poms-parent/master/poms-dependencies.svg, window="_blank"]


=== source code repositories

The artifacts in 'sharable utilities' are  available on maven central and their source code is available on github.  Thich makes them useable also by other parties then https://github.com/vpro[VPRO]

The image is clickable and links to several version control repositories.

The azure blocks we consider part of the 'poms ecosystem'. The ones with blue links are open source, and point to public repositories. The green links point to private repositories.

== Operations and development

=== Configuration files and context root

For every deployable we indicate:
The URL in test/acc and production
The port and application context we suggest for development. Configure your application like this and you would have minimal configuration to do to get things up and running on your development machine.

The configuration file that is automaticly included and we suggest for development. We suggest that you maintain configuration you need for development in this file.

We often support a setting like this:
env=[prod|acc|test|localhost] to automaticly switch between several setting which vary between environments predictably.

[options="header"]
|========
| project |url |configuration file |recommended port and context during development
| https://github.com/npo-poms/functional-tests[Functional Tests] | | `${user.home}/conf/npo-functional-tests.properties` | -

| https://git.vpro.nl/npo/media/-/tree/master/media-server[GUI] | https://poms.omroep.nl/[https://poms{otap}.omroep.nl/] | `${user.home}/conf/media.properties` | http://localhost:8071/[8071]

| https://git.vpro.nl/npo/media/-/tree/master/media-rs[Backend] | https://api.poms.omroep.nl[https://api{otap}.poms.omroep.nl/] | `${user.home}/conf/media-rs.properties` | http://localhost:8071/rs[8071/rs]

| https://git.vpro.nl/npo/api[Frontend API]| https://rs.poms.omroep.nl/v1[https://rs{otap}.poms.omroep.nl/v1] | `${user.home}/conf/npo-api.properties` | http://localhost:8071/v1[8070/v1]

| https://git.vpro.nl/npo/pages-publish[Page publisher API]| https://publish.pages.omroep.nl[https://publish{otap}.pages.omroep.nl/v1] | `${user.home}/conf/page-publish.properties` | http://localhost:8069[8069]

| https://git.vpro.nl/npo/npo-publish[Publisher] | - | `${user.home}/conf/npo-publisher.properties` | -

| https://git.vpro.nl/npo/images/-/tree/master/image-server-frontend[Images Frontend] | https://images.poms.omroep.nl[https://images{otap}.poms.omroep.nl/] | `${user.home}/conf/images-frontend.properties` | 8072

| https://git.vpro.nl/npo/images/-/tree/master/image-server[Images Backend] | https://poms.omroep.nl/images[https://poms{otap}.omroep.nl/images] | `${user.home}/conf/images.properties` | http://localhost:8071/images/[8071/images]
|========

=== Projects
==== Functional Tests

See https://github.com/npo-poms/functional-tests

==== GUI and Backend RestServices

Currently the POMS GUI and the POMS Backend API are maintained as one project with two artifacts, which are also always deployed in one tomcat. It would actually be a good idea to deploy the backend API seperately and also redundant. We may do this on the new hosting solution.

We may also split up the project in SCM then.

==== Frontend API

==== Page publisher API

==== Publisher API

==== NPO API Clients

This project provides java clients for the above projects.

==== VPRO shared

Most projects also depend on a collection of utilities maintained by VPRO but which are not specific for POMS or its subsystems.
See https://github.com/vpro/vpro-shared

==== POMS shared

These modules are specific for POMS, and most noticably contain the domain classes shared by most projects, like the 'domain' objects and services.
See https://github.com/npo-poms/poms-shared

Classes from this may also end up outside the POMS projects themselves. Like e.g. CMS's (probably via the api clients)

==== Backend utilities

Sometimes different POMS project share 'backend' code, like repository implementations. These need never be exposed to the outside world.

==== User backend

This contains the code to talk to keycloak to acquire user roles/groups

== Rights

The rights matrix of the POMs GUI can be found link:RIGHTS.html[here]
